### ISSUE TITLE
Contact: let's share efforts to implement 'mxgraph-type-definitions'

### ISSUE THREAD

**Issue by tbouffard** [hungtcs/mxgraph-type-definitions#1]
Hi,
I am contacting you to propose my help (and probably additional help from some of my colleagues) to work with you on this project. My goal is to have a mxgraph types definition directly available in DefinitelyTyped, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5317

Currently, there are a lot of repositories that try to develop an attempt for such types but none reach completeness and the efforts are spread all around instead of mutualizing everyone energy on a single solution.

I have recently found your repository: it looks like very promising and you are currently actively working on it.
I especially like the fact that, unlike other repositories, you define a definition file per mxgraph class. IMHO, this is a huge benefits in the maintainability field: it will be easier to know where to look/go when a new function is added to mxgraph and must be reflect to the types definition. This will avoid having a very large definition file as mxgraph defines a lot of types, so this will also easier to navigate and have a look at the code.

Here is a list of repositories I know that try to achieve types definition for mxgraph (they all miss a lot of functions and it is unclear which mxgraph they target)
- https://github.com/lgleim/mxgraph-typings and more 25 forks (most don’t provide any new stuffs)
- https://github.com/rabpeter/ts-mxgraph-typings (a copy of lgleim with some additions, probably the most up to date)

Currently, these repositories have an advantage on yours: they added documentation to class/function which helps when using an IDE. However, this documentation is directly copied from the mxgraph source code, so it is not fully JSDoc compliant.
I think this in an area on which your current implementation may be improved and I could help on this (among other thing)

I hope to hear from you soon
Thomas

**Comment by hungtcs** [comment]
Hi @tbouffard, 
The content of this repository is currently very imperfect, most of these files comes from [mxGraph API Specification], I don't have any special maintenance, just supplement it when I need to use the missing parts.

It's a great honor to work with you, what should I do now? I have no experience of working with other people on GitHub.

[mxGraph API Specification]: https://jgraph.github.io/mxgraph/docs/js-api/files/index-txt.html

**Comment by tbouffard** [comment]
hello @hungtcs 
good news

For now, there is nothing special to do on the repository on your side (in the following I added links to the GitHub help in case you need information about the way contributions can be done).

I am going to [fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks) it, do some changes and propose a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) that you would be able to [review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests) and eventually [merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-changes-from-a-pull-request) into your repository

As 1st attempt, I am going to have a look at the `shape` folder.

**Comment by tbouffard** [comment]
1st contribution now available for review and discussion, see #2

**Comment by hungtcs** [comment]
Hi @tbouffard! #2 is merged. And my local project has some uncommitted changes to the shape module, which are now merged.

**Comment by tbouffard** [comment]
@hungtcs thanks again for the merge

I have started an effort to have mxGraph TypeScript available through DefinitelyTyped, see https://github.com/process-analytics/mxgraph-road-to-DefinitelyTyped
Will you ok to join me on this?

I have proposed your repository as the working place to implement the definitions, I guess that for now, this shouldn't change anything for you except that you may receive more contributions and some discussions may happen about the definitions implementation

**Comment by hungtcs** [comment]
@tbouffard My pleasure :smiley:

**Comment by tbouffard** [comment]
Great, I have udpated the readme of the followup repo.
I close his PR as we are done on this subject.
