### ISSUE TITLE
chore: push git tag to track version changes

### ISSUE THREAD

**Issue by tbouffard** [hungtcs/mxgraph-type-definitions#12]
Currently, it is very hard to know what are the changes between version. New versions are published to npmjs but we cannot track the related commits and change on the git repository.

Here is the list of versions with the commit I detected within the git history comparing the npm package date and commit date
- 1.0.2: a92fd70
- 1.0.1: bbc8718b894ea49926a1a63a4302f60743ff4080 (commit 2020-03-18T06:09:30Z, npm package 2020-03-18T06:10:43.530Z)
- 1.0.0: ebde1b1f1020146ee11a520fd34d4fe116865b49 introduce package.json file with version 1.0.0 (commit 2019-12-19T08:41:50Z, npm package 2019-12-19T08:41:58.136Z)

For the future versions, the [npm version command](https://docs.npmjs.com/cli/version) could be used to upgrade version bump easily
- `npm version ...` to update the packag json file and create the git tag
- then run `git push && git push --tags`

If accepted, this could be at least documented in the README (new release section)

Having git tag will also allow us to add a badge like the following to let user see version history directly on GitHub: [![GitHub release (latest by date including pre-releases)](https://img.shields.io/github/v/release/hungtcs/mxgraph-type-definitions?color=orange&include_prereleases)](https://github.com/hungtcs/mxgraph-type-definitions/releases)

**Comment by hungtcs** [comment]
Thank you @tbouffard, I will follow these specifications in future versions, thank you very much for these suggestions, this is very helpful to me.
